// source: user.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

import * as jspb from 'google-protobuf';//后
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.myapp.MsgMeetingSceneRule', null, global);
goog.exportSymbol('proto.myapp.User', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.myapp.User = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.myapp.User, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.myapp.User.displayName = 'proto.myapp.User';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.myapp.MsgMeetingSceneRule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.myapp.MsgMeetingSceneRule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.myapp.MsgMeetingSceneRule.displayName = 'proto.myapp.MsgMeetingSceneRule';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.myapp.User.prototype.toObject = function(opt_includeInstance) {
  return proto.myapp.User.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.myapp.User} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.User.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    age: jspb.Message.getFieldWithDefault(msg, 2, 0),
    email: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.myapp.User}
 */
proto.myapp.User.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.myapp.User;
  return proto.myapp.User.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.myapp.User} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.myapp.User}
 */
proto.myapp.User.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setAge(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.myapp.User.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.myapp.User.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.myapp.User} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.User.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAge();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.myapp.User.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.User} returns this
 */
proto.myapp.User.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 age = 2;
 * @return {number}
 */
proto.myapp.User.prototype.getAge = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.myapp.User} returns this
 */
proto.myapp.User.prototype.setAge = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string email = 3;
 * @return {string}
 */
proto.myapp.User.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.myapp.User} returns this
 */
proto.myapp.User.prototype.setEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.myapp.MsgMeetingSceneRule.prototype.toObject = function(opt_includeInstance) {
  return proto.myapp.MsgMeetingSceneRule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.myapp.MsgMeetingSceneRule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.MsgMeetingSceneRule.toObject = function(includeInstance, msg) {
  var f, obj = {
    isrun: jspb.Message.getFieldWithDefault(msg, 1, 0),
    isjump: jspb.Message.getFieldWithDefault(msg, 2, 0),
    isformalwear: jspb.Message.getFieldWithDefault(msg, 3, 0),
    ismask: jspb.Message.getFieldWithDefault(msg, 4, 0),
    isaudiencearealimit: jspb.Message.getFieldWithDefault(msg, 5, 0),
    isenterspeecharea: jspb.Message.getFieldWithDefault(msg, 6, 0),
    ismeetingstartcanmove: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.myapp.MsgMeetingSceneRule}
 */
proto.myapp.MsgMeetingSceneRule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.myapp.MsgMeetingSceneRule;
  return proto.myapp.MsgMeetingSceneRule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.myapp.MsgMeetingSceneRule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.myapp.MsgMeetingSceneRule}
 */
proto.myapp.MsgMeetingSceneRule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsrun(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsjump(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsformalwear(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsmask(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsaudiencearealimit(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsenterspeecharea(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsmeetingstartcanmove(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.myapp.MsgMeetingSceneRule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.myapp.MsgMeetingSceneRule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.myapp.MsgMeetingSceneRule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.myapp.MsgMeetingSceneRule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIsrun();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getIsjump();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getIsformalwear();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getIsmask();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getIsaudiencearealimit();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getIsenterspeecharea();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getIsmeetingstartcanmove();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
};


/**
 * optional int32 isRun = 1;
 * @return {number}
 */
proto.myapp.MsgMeetingSceneRule.prototype.getIsrun = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.myapp.MsgMeetingSceneRule} returns this
 */
proto.myapp.MsgMeetingSceneRule.prototype.setIsrun = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 isJump = 2;
 * @return {number}
 */
proto.myapp.MsgMeetingSceneRule.prototype.getIsjump = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.myapp.MsgMeetingSceneRule} returns this
 */
proto.myapp.MsgMeetingSceneRule.prototype.setIsjump = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 isFormalWear = 3;
 * @return {number}
 */
proto.myapp.MsgMeetingSceneRule.prototype.getIsformalwear = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.myapp.MsgMeetingSceneRule} returns this
 */
proto.myapp.MsgMeetingSceneRule.prototype.setIsformalwear = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 isMask = 4;
 * @return {number}
 */
proto.myapp.MsgMeetingSceneRule.prototype.getIsmask = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.myapp.MsgMeetingSceneRule} returns this
 */
proto.myapp.MsgMeetingSceneRule.prototype.setIsmask = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional int32 isAudienceAreaLimit = 5;
 * @return {number}
 */
proto.myapp.MsgMeetingSceneRule.prototype.getIsaudiencearealimit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.myapp.MsgMeetingSceneRule} returns this
 */
proto.myapp.MsgMeetingSceneRule.prototype.setIsaudiencearealimit = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int32 isEnterSpeechArea = 6;
 * @return {number}
 */
proto.myapp.MsgMeetingSceneRule.prototype.getIsenterspeecharea = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.myapp.MsgMeetingSceneRule} returns this
 */
proto.myapp.MsgMeetingSceneRule.prototype.setIsenterspeecharea = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 isMeetingStartCanMove = 7;
 * @return {number}
 */
proto.myapp.MsgMeetingSceneRule.prototype.getIsmeetingstartcanmove = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.myapp.MsgMeetingSceneRule} returns this
 */
proto.myapp.MsgMeetingSceneRule.prototype.setIsmeetingstartcanmove = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


// goog.object.extend(exports, proto.myapp);
export default {
  ...proto.myapp,
};//后
